# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 993d936f8e85333ab2176c300b1243a1c60cf08ed6c499a70981af6a6c3b1ee35fd7a715b1179fc42e78d9952fdf580bca030feecff7cd12fe4c559ad18d55ec
  twitter_api_key: NffKxWmw5SLbsQGhjbhglALhF
  twitter_api_secret: DK5ruZLHREujag2oPPC5Kth5FFWjD0LcKamntkfexUjvd6sJj3

test:
  secret_key_base: 5b86225e6e24566df9e5b722f47d8ea5138e6d8343c1dee9ea71c4558d10943035c997c4911da40fcbc4ad464683e5ef7c11e847a669e413c084819988a88ee4
  twitter_api_key: NffKxWmw5SLbsQGhjbhglALhF
  twitter_api_secret: DK5ruZLHREujag2oPPC5Kth5FFWjD0LcKamntkfexUjvd6sJj3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: NffKxWmw5SLbsQGhjbhglALhF
  twitter_api_secret: DK5ruZLHREujag2oPPC5Kth5FFWjD0LcKamntkfexUjvd6sJj3
